// <auto-generated />
namespace SmartSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202008301510498_createModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
